#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if [ ! -f ~/.vimrc ]
then
	echo "~/.vimrc must be present"
	exit 1
fi

echo "Copying .vimrc to repo"
cp ~/.vimrc ./vimrc

exit 0
